{
  "services": 
    "stirling-pdf": 
      "name": "Stirling-PDF",
      "image": "rvalen1123/stirling-pdf",
      "envVars": 
        "DOCKER_ENABLE_SECURITY": "true",
        "LANGS": "en_US,es-mx,fa",
        "OCR_ENABLED": "true",
        "ENABLE_EXTERNAL_DB": "true",
        "ENABLE_FOLDER_SCAN": "true",
        "SIGNING_ENABLED": "true",
        "DATABASE_URL": "${{ DATABASE_URL }}"
      },
      "volumes": 
        "./StirlingPDF/trainingData": "/usr/share/tesseract-ocr/4.00/tessdata",
        "./StirlingPDF/extraConfigs": "/configs",
        "./StirlingPDF/customFiles": "/customFiles",
        "./StirlingPDF/logs": "/logs",
        "./StirlingPDF/pipeline": "/pipeline",
        "./StirlingPDF/storage": "/app/storage",
        "./StirlingPDF/input": "/app/input",
        "./StirlingPDF/output": "/app/output"
      },
      "ports": 
        "8080": 
          "protocol": "http"
        }
      }
    }
  }
}
